### ISSUE TITLE
Add option to choose different tokens

### ISSUE THREAD

**Issue by cryptobugbear** [chiliagons/gnuswap#2]
Currently there is no support for multi tokens - Implement a drop-down to select different tokens that are available in the gnosis multisig wallet. Also incorporate other UI changes as per request from Gnosis.

Also only show the network where we are sending it to , auto detect current network

**Comment by nicchunglow** [comment]
Noted on the token options. 
Will work with 
​/safes​/{address}​/balances​/. 

Do let me know if there are more information on the UI changes.
