### ISSUE TITLE
Transaction List - Implementation

### ISSUE THREAD

**Issue by cryptobugbear** [chiliagons/gnuswap#4]
The transaction list should be implemented - currently it is just a place holder. Additional functions such as Retry should be available if available in https://github.com/connext/nxtp

**Comment by cryptobugbear** [comment]
Data needs to be rendered in second tab and tested

**Comment by Aman-zishan** [comment]
Added `historical` Table to transaction page

- [ ] Add active transaction
- [ ] Loading screen while fetching data
